---
title: "Stress prediction using IBI"
author: "Deepak Sharma"
date: "March 20, 2017"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set( echo = FALSE,
	message = FALSE, warning = FALSE
)

```

Predict stress using IBI (Inter Beat Interval) data.

## Importing and subsetting data

```{r Import library and data, echo=FALSE, message=FALSE, warning=FALSE}

# Importing Dr. Shashi data

require(XLConnect)

di <- read.xlsx("~/AIIMS work/Stress_analysis/Datasets/27-1-15 dr indrajeet(M).xlsx",sheetIndex = 1,header = TRUE)

# Filtering range

min_ibi <- 400
max_ibi <- 800
margin <- 50

# Subsetting

first <- margin
di_ibi <- as.numeric(di$IBI)
times <- di$LocalTime
lasttime <- tail(times[!is.na(times)], 1)
last <- which(times == lasttime)
last <- last - x

di_ibi <- di_ibi[first:last]
a <- as.numeric(subset(di_ibi, di_ibi >= min_ibi & di_ibi < max_ibi ))
cat("Range of IBI (Min, Max) : ", range(di_ibi))
cat("Standard deviation of complete dataset: ", sd(di_ibi))
cat("Standard deviation of subset : ", sd(a))
y <- fft(as.numeric(a))

```

## Visualizing results

```{r Visualize results, echo=FALSE, message=FALSE, warning=FALSE}

plot(1:last,fft(di_ibi),type = 'l')
plot(a,type='l')
hist(a,breaks = 200)

```

